version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

kos:
  - main: ./
    working_dir: .

    platforms:
      - linux/amd64
      - linux/arm64

    tags:
      - '{{ if not .Prerelease }}latest{{ end }}'
      - '{{.Tag}}'

    labels:
      org.opencontainers.image.created: "{{.Date}}"
      org.opencontainers.image.name: "{{.ProjectName}}"
      org.opencontainers.image.revision: "{{.FullCommit}}"
      org.opencontainers.image.version: "{{.Version}}"
      org.opencontainers.image.source: "{{.GitURL}}"

    sbom: none

    bare: true

gomod:
  proxy: false

release:
  draft: false
